### ISSUE TITLE
Improve backward-compatibility testing

### ISSUE THREAD

**Issue by jpountz** [apache/lucene#12956]
### Description

#12895 highlighted that our backward compatibility tests could use some love. I reviewed what we have and tried to collect a list of things we should improve:
 - [ ] Add backward indexes created with `BEST_COMPRESSION`. Currently, all indexes we create use the default `BEST_SPEED`.
 - [ ] Restore write logic of old FST versions. #12908 added support for the last version back, but there are older versions we should add back as well so that we can test them properly through `BasePostingsFormatTestCase`.
 - [ ] Restore write logic of old BKDWriter versions. Likewise, but for BKD trees. Restoring them would allow us to test them through `BasePointsFormatTestCase`.
 - [x] Add tests with real data to `BasePostingsFormatTestCase`. (done via #12925)
 - [x] Add tests with real data to `BaseStoredFieldsFormatTestCase`. #12927
